# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\thirdStacking.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import QUrl,QDesktopServices


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        MainWindow.setStyleSheet("background-color:#030303")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(200, 600))
        self.widget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.widget.setStyleSheet("background-color:#212121;")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setMinimumSize(QtCore.QSize(200, 325))
        self.frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 51, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\UI\\menu.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(70, 20, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_2.setStyleSheet("color:white;\n"
"")
        self.label_2.setObjectName("label_2")
        self.home_button = QtWidgets.QPushButton(self.frame)
        self.home_button.setGeometry(QtCore.QRect(0, 100, 200, 75))
        self.home_button.setMinimumSize(QtCore.QSize(200, 0))
        self.home_button.setMaximumSize(QtCore.QSize(250, 16777215))
        self.home_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_button.setStyleSheet("color:white;\n"
"font-size:20px;\n"
"background-color:#3d3d3d;\n"
"border:0px;\n"
"margin:0px;\n"
"padding:0px;\n"
"text-align:left;\n"
"padding-left:10px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\UI\\home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_button.setIcon(icon)
        self.home_button.setIconSize(QtCore.QSize(32, 32))
        self.home_button.setObjectName("home_button")
        self.settings_button = QtWidgets.QPushButton(self.frame)
        self.settings_button.setGeometry(QtCore.QRect(0, 175, 200, 75))
        self.settings_button.setMinimumSize(QtCore.QSize(200, 0))
        self.settings_button.setMaximumSize(QtCore.QSize(250, 16777215))
        self.settings_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settings_button.setStyleSheet("color:white;\n"
"font-size:20px;\n"
"\n"
"border:0px;\n"
"margin:0px;\n"
"padding:0px;\n"
"text-align:left;\n"
"padding-left:10px;\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\UI\\settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_button.setIcon(icon1)
        self.settings_button.setIconSize(QtCore.QSize(32, 32))
        self.settings_button.setObjectName("settings_button")
        self.help_button = QtWidgets.QPushButton(self.frame)
        self.help_button.setGeometry(QtCore.QRect(0, 250, 200, 75))
        self.help_button.setMinimumSize(QtCore.QSize(200, 0))
        self.help_button.setMaximumSize(QtCore.QSize(250, 16777215))
        self.help_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.help_button.setStyleSheet("color:white;\n"
"font-size:20px;\n"
"\n"
"border:0px;\n"
"margin:0px;\n"
"padding:0px;\n"
"text-align:left;\n"
"padding-left:10px;\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\UI\\help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help_button.setIcon(icon2)
        self.help_button.setIconSize(QtCore.QSize(32, 32))
        self.help_button.setObjectName("help_button")
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setMinimumSize(QtCore.QSize(200, 150))
        self.frame_2.setMaximumSize(QtCore.QSize(250, 150))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.github_button = QtWidgets.QPushButton(self.frame_2)
        self.github_button.setGeometry(QtCore.QRect(0, 0, 200, 75))
        self.github_button.setMinimumSize(QtCore.QSize(200, 0))
        self.github_button.setMaximumSize(QtCore.QSize(250, 16777215))
        self.github_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.github_button.setStyleSheet("color:#c0c0c0;\n"
"font-size:20px;\n"
"\n"
"border:0px;\n"
"margin:0px;\n"
"padding:0px;\n"
"text-align:left;\n"
"padding-left:10px;\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\UI\\github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.github_button.setIcon(icon3)
        self.github_button.setIconSize(QtCore.QSize(32, 32))
        self.github_button.setObjectName("github_button")
        self.linkedin_button = QtWidgets.QPushButton(self.frame_2)
        self.linkedin_button.setGeometry(QtCore.QRect(0, 75, 200, 75))
        self.linkedin_button.setMinimumSize(QtCore.QSize(200, 0))
        self.linkedin_button.setMaximumSize(QtCore.QSize(250, 16777215))
        self.linkedin_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.linkedin_button.setStyleSheet("color:#c0c0c0;\n"
"font-size:20px;\n"
"\n"
"border:0px;\n"
"margin:0px;\n"
"padding:0px;\n"
"text-align:left;\n"
"padding-left:10px;\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\UI\\Linkedin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.linkedin_button.setIcon(icon4)
        self.linkedin_button.setIconSize(QtCore.QSize(32, 32))
        self.linkedin_button.setObjectName("linkedin_button")
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.widget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.label_3 = QtWidgets.QLabel(self.home_page)
        self.label_3.setGeometry(QtCore.QRect(106, 209, 381, 161))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.home_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.label_4 = QtWidgets.QLabel(self.settings_page)
        self.label_4.setGeometry(QtCore.QRect(70, 250, 431, 231))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_4.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.settings_page)
        self.help_page = QtWidgets.QWidget()
        self.help_page.setObjectName("help_page")
        self.label_5 = QtWidgets.QLabel(self.help_page)
        self.label_5.setGeometry(QtCore.QRect(60, 280, 511, 191))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(3, 3, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.help_page)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.home_button.clicked.connect(lambda: self.handleMenu(0))
        self.settings_button.clicked.connect(lambda: self.handleMenu(1))
        self.help_button.clicked.connect(lambda: self.handleMenu(2))

        # The Link to My-My
        github_url = QUrl("https://github.com/ACHREF999")
        linkedin_url = QUrl("https://google.com")

        self.github_button.clicked.connect(lambda: QDesktopServices.openUrl(github_url))

        self.linkedin_button.clicked.connect(lambda: QDesktopServices.openUrl(linkedin_url))

    def handleMenu(self, index):
        self.stackedWidget.setCurrentIndex(index)
        if index == 0:
            self.settings_button.setStyleSheet("color:white;\n"
                                               "font-size:20px;\n"
                                               "\n"
                                               "border:0px;\n"
                                               "margin:0px;\n"
                                               "padding:0px;\n"
                                               "text-align:left;\n"
                                               "padding-left:10px;\n"
                                               "")
            self.help_button.setStyleSheet("color:white;\n"
                                           "font-size:20px;\n"
                                           "\n"
                                           "border:0px;\n"
                                           "margin:0px;\n"
                                           "padding:0px;\n"
                                           "text-align:left;\n"
                                           "padding-left:10px;\n"
                                           "")
            self.home_button.setStyleSheet("color:white;\n"
                                           "font-size:20px;\n"
                                           "background-color:#3d3d3d;\n"
                                           "border:0px;\n"
                                           "margin:0px;\n"
                                           "padding:0px;\n"
                                           "text-align:left;\n"
                                           "padding-left:10px;")

            pass
        elif index == 1:
            self.home_button.setStyleSheet("color:white;\n"
                                           "font-size:20px;\n"
                                           "\n"
                                           "border:0px;\n"
                                           "margin:0px;\n"
                                           "padding:0px;\n"
                                           "text-align:left;\n"
                                           "padding-left:10px;\n"
                                           "")
            self.help_button.setStyleSheet("color:white;\n"
                                           "font-size:20px;\n"
                                           "\n"
                                           "border:0px;\n"
                                           "margin:0px;\n"
                                           "padding:0px;\n"
                                           "text-align:left;\n"
                                           "padding-left:10px;\n"
                                           "")
            self.settings_button.setStyleSheet("color:white;\n"
                                               "font-size:20px;\n"
                                               "background-color:#3d3d3d;\n"
                                               "border:0px;\n"
                                               "margin:0px;\n"
                                               "padding:0px;\n"
                                               "text-align:left;\n"
                                               "padding-left:10px;")
            pass
        elif index == 2:
            self.settings_button.setStyleSheet("color:white;\n"
                                               "font-size:20px;\n"
                                               "\n"
                                               "border:0px;\n"
                                               "margin:0px;\n"
                                               "padding:0px;\n"
                                               "text-align:left;\n"
                                               "padding-left:10px;\n"
                                               "")
            self.home_button.setStyleSheet("color:white;\n"
                                           "font-size:20px;\n"
                                           "\n"
                                           "border:0px;\n"
                                           "margin:0px;\n"
                                           "padding:0px;\n"
                                           "text-align:left;\n"
                                           "padding-left:10px;\n"
                                           "")
            self.help_button.setStyleSheet("color:white;\n"
                                           "font-size:20px;\n"
                                           "background-color:#3d3d3d;\n"
                                           "border:0px;\n"
                                           "margin:0px;\n"
                                           "padding:0px;\n"
                                           "text-align:left;\n"
                                           "padding-left:10px;")
            pass
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Menu"))
        self.home_button.setText(_translate("MainWindow", "  Home"))
        self.settings_button.setText(_translate("MainWindow", "  Settings"))
        self.help_button.setText(_translate("MainWindow", "  Help"))
        self.github_button.setText(_translate("MainWindow", "ACHREF999"))
        self.linkedin_button.setText(_translate("MainWindow", "ACHREF999"))
        self.label_3.setText(_translate("MainWindow", "Home Page"))
        self.label_4.setText(_translate("MainWindow", "Settings Page"))
        self.label_5.setText(_translate("MainWindow", "Help Page"))
